
import type { NextPage } from 'next';
import { GetServerSideProps } from 'next';
import Head from 'next/head';

import { getById } from '@services/omdb';
import { FullResult } from '@services/omdb/types';

import Movie from '@components/feature/Movie';

interface MoviePageProps {
    data: FullResult
}

const MoviePage = ({ data }: MoviePageProps) => {
    const { Title } = data ?? {};

    return (
        <div>
            <Head>
                <title>Movie | {Title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Movie {...data} />
        </div>
    )
}



// This gets called on every request
export const getServerSideProps: GetServerSideProps = async ({ params }) => {
    const { id = '' } = params ?? {};
    // Fetch data from external API
    const data = await getById({ i: id as string })

    // Pass data to the page via props
    return { props: { data } }
}

export default MoviePage;